### ISSUE TITLE
Missing permissions in helm ClusterRole

### ISSUE THREAD

**Issue by erdody** [xco-sk/eck-custom-resources#33]
There are a few permissions missing in the [helm chart ClusterRole template](https://github.com/xco-sk/eck-custom-resources/blob/main/charts/eck-custom-resources-operator/templates/role.yaml). These are the ones I found so far:
```yaml
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
```

plus all the ones associated with leader election (ConfigMap, etc.)
