### ISSUE TITLE
add compatibility for 7.1x Elastic

### ISSUE THREAD

**Issue by MrTolerant** [xco-sk/eck-custom-resources#41]
Add posibility to create **SnapshotRepository** for Elasticsearch   version: 7.17.4

Now when i try to create  SnapshotRepository
Helm release values:
```
  values:
    fullnameOverride: es-logging-custom-resources-operator
    elasticsearch:
      enabled: true
      url: http://es-logging-es-http:9200/
      certificate:
        secretName: es-logging-es-http-certs-public
        certificateKey: ca.crt
      authentication:
        usernamePasswordSecret:
          secretName: es-logging-es-elastic-user
          userName: elastic
    kibana:
      enabled: false

```

```
apiVersion: es.eck.github.com/v1alpha1
kind: SnapshotRepository
metadata:
  name: es-audit-azure-backup
  namespace: es-audit
spec:
  body: |
    {
      "type": "azure",
      "settings":
      {
        "container": "es-audit",
        "base_path" : "/"
      }
    }
   ``` 
i got error:
```
1.6666965462157245e+09	ERROR	controller.snapshotrepository	Reconciler error	{"reconciler group": "es.eck.github.com", "reconciler kind": "SnapshotRepository", "name": "es-iam-azure-backup", "namespace": "es-iam", "error": "error(status: 500, response: [500 Internal Server Error] {\"error\":{\"root_cause\":[{\"type\":\"settings_exception\",\"reason\":\"Unable to find client with name [default]\"}],\"type\":\"repository_verification_exception\",\"reason\":\"[es-iam-azure-backup] path  is not accessible on master node\",\"caused_by\":{\"type\":\"settings_exception\",\"reason\":\"Unable to find client with name [default]\"}},\"status\":500})"}
```
