### ISSUE TITLE
Kibana Instance certificate issue - x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kemil-sakhareliya** [xco-sk/eck-custom-resources#51]
Hi!

I am facing this issue **x509: certificate signed by unknown authority** while adding dataview object

we use elastic cloud and we have https endpoint for Kibana. I downloaded the certificate from 
ElasticSearch --> deployment --> security --> CA certificates 

I added the certificate in a secret inside kubernetes and added that secret name and key in the kibana instance.

**Kibana Instance:**
```
apiVersion: kibana.eck.github.com/v1alpha1
kind: KibanaInstance
metadata:
  name: kibana-instance
  namespace: elk-beats
spec:
  enabled: true
  url: https://..
  certificate:
    secretName: eck-kibana-instance-crt
    certificateKey: ca.crt
  authentication:
    usernamePasswordSecret:
      secretName: eck-operator-secret
      userName: username
```

**DataView:**
```
apiVersion: kibana.eck.github.com/v1alpha1
kind: DataView
metadata:
  name: test-dataview
  namespace: elk-beats
spec:
  targetInstance:
    name: kibana-instance
  body: |
    {
      "title": "test-dataview*",
      "timeFieldName": "@timestamp",
    }
```

**Error:**
`1.681221625623375e+09	DEBUG	events	Warning	{"object": {"kind":"DataView","namespace":"elk","name":"test-dataview","uid":"83e90","apiVersion":"kibana.eck.github.com/v1alpha1","resourceVersion":"374169829"}, "reason": "Failed to create/update", "message": "Failed to create/update kibana.eck.github.com/v1alpha1/DataView test-dataview: Get \"https://dgdg": x509: certificate signed by unknown authority"}`

OR is there any way I can disable ssl verification as we can do with filebeat like for ex:
**ssl.verification_mode: none**

Please let me know what is going wrong. 

Thanks.
