### ISSUE TITLE
allow yaml instead of json body

### ISSUE THREAD

**Issue by an-tex** [xco-sk/eck-custom-resources#57]
currently to e.g. create a snapshot repository you'd write
```yaml
apiVersion: es.eck.github.com/v1alpha1
kind: SnapshotRepository
metadata:
  name: snapshotrepository-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  body: |
    {
      "type": "fs",
      "settings": {
        "location": "/tmp/"
      }
    }
```

meaning the actual configuration is written in json. the downside of this approach is that you can't use tools like kustomize to e.g. define a base snapshot repository with it's settings and then override it only partially in an overlay. to overcome this limitation one could allow (untyped) yaml and just transform it to the same json. 

then you could define sth like:

```yaml
apiVersion: es.eck.github.com/v1alpha1
kind: SnapshotRepository
metadata:
  name: snapshotrepository-sample
spec:
  targetInstance:
    name: elasticsearch-quickstart
  settings: # or some better name?
    type: fs
    settings:
      location: "/tmp"
```
